/* ══════════════════════════════════════════════════════
   Download Helpers — Shell script, ZIP & file download
   ══════════════════════════════════════════════════════ */

import JSZip from "jszip";

/**
 * Generates a shell script that recreates all project files.
 *
 * @param {string} projName - Sanitized project name
 * @param {Object<string, string>} files - Map of path → content
 * @returns {string} Shell script content
 */
export function generateShellScript(projName, files) {
  const entries = Object.entries(files);
  if (!entries.length) return "";

  let sh = `#!/bin/bash\n# ${projName} - Generated by DevHive AI Platform\n# Run: bash setup.sh\n\nmkdir -p ${projName}\ncd ${projName}\n\n`;

  entries.forEach(([path, content]) => {
    const dir = path.includes("/") ? path.substring(0, path.lastIndexOf("/")) : "";
    if (dir) sh += `mkdir -p "${dir}"\n`;
    sh += `cat > "${path}" << 'ENDOFFILE'\n${content}\nENDOFFILE\n\n`;
  });

  sh += `\necho "✅ ${projName} created!"\necho "Run: cd ${projName} && npm install"\n`;
  return sh;
}

/**
 * Generates a ZIP blob containing all project files.
 *
 * @param {string} projName - Project name (root folder in ZIP)
 * @param {Object<string, string>} files - Map of path → content
 * @returns {Promise<Blob>} ZIP blob
 */
export async function generateZipBlob(projName, files) {
  const zip = new JSZip();
  const root = zip.folder(projName);

  Object.entries(files).forEach(([path, content]) => {
    root.file(path, content);
  });

  return zip.generateAsync({ type: "blob", compression: "DEFLATE" });
}

/**
 * Triggers browser download for arbitrary text content.
 *
 * @param {string} filename - Download filename
 * @param {string} content  - File content
 * @param {string} [mime]   - MIME type (default: text/plain)
 */
export function downloadBlob(filename, content, mime = "text/plain") {
  const blob = new Blob([content], { type: mime });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}

/**
 * Downloads a Blob directly (for ZIP files).
 *
 * @param {string} filename
 * @param {Blob} blob
 */
export function downloadBlobDirect(filename, blob) {
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}

/**
 * Copies text to the system clipboard.
 *
 * @param {string} text
 * @returns {Promise<void>}
 */
export function copyToClipboard(text) {
  return navigator.clipboard.writeText(text);
}
